name: Simple CI Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo message after push
        run: echo "✅ Push realizado com sucesso!"
